### ISSUE TITLE
Error after successful login: "form.requestSubmit is not a function", OSX Safari only

### ISSUE THREAD

**Issue by dprkr** [Nodewood/issues#2]
See below.  I did not get the error on Chrome or Firefox.

```
TypeError: form.requestSubmit is not a function. (In 'form.requestSubmit()', 'form.requestSubmit' is undefined)
formSubmit — TextInput.vue:142
formSubmit
invokeWithErrorHandling — vue.runtime.esm.js:1854
```

<img width="570" alt="2021-03-02_20-40-41" src="https://user-images.githubusercontent.com/9397549/109739870-481c6d00-7b98-11eb-9c39-8c88271b7a28.png">

<img width="908" alt="2021-03-02_17-44-57" src="https://user-images.githubusercontent.com/9397549/109739884-4d79b780-7b98-11eb-911a-4fe12addd537.png">

**Comment by DanHulton** [comment]
Huh, it looks like Safari doesn't support `formSubmit`, only `submit`.

Added feature detection for this call, and fixed in 0.16.1.
